// Code generated by thriftrw

package loadbalancer

import (
	"errors"
	"fmt"
	"github.com/bombela/yarpc-go-fun/broker"
	"github.com/thriftrw/thriftrw-go/wire"
	"strings"
)

type BackendsArgs struct{}

func (v *BackendsArgs) ToWire() (wire.Value, error) {
	var (
		fields [0]wire.Field
		i      int = 0
	)
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *BackendsArgs) FromWire(w wire.Value) error {
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		}
	}
	return nil
}

func (v *BackendsArgs) String() string {
	var fields [0]string
	i := 0
	return fmt.Sprintf("BackendsArgs{%v}", strings.Join(fields[:i], ", "))
}

func (v *BackendsArgs) MethodName() string {
	return "backends"
}

func (v *BackendsArgs) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

type BackendsResult struct {
	Success []*broker.BackendStatus `json:"success"`
}

type _List_BackendStatus_ValueList []*broker.BackendStatus

func (v _List_BackendStatus_ValueList) ForEach(f func(wire.Value) error) error {
	for _, x := range v {
		w, err := x.ToWire()
		if err != nil {
			return err
		}
		err = f(w)
		if err != nil {
			return err
		}
	}
	return nil
}

func (v _List_BackendStatus_ValueList) Size() int {
	return len(v)
}

func (_List_BackendStatus_ValueList) ValueType() wire.Type {
	return wire.TStruct
}

func (_List_BackendStatus_ValueList) Close() {
}

func (v *BackendsResult) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Success != nil {
		w, err = wire.NewValueList(_List_BackendStatus_ValueList(v.Success)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}
	if i != 1 {
		return wire.Value{}, fmt.Errorf("BackendsResult should have exactly one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _BackendStatus_Read(w wire.Value) (*broker.BackendStatus, error) {
	var v broker.BackendStatus
	err := v.FromWire(w)
	return &v, err
}

func _List_BackendStatus_Read(l wire.ValueList) ([]*broker.BackendStatus, error) {
	if l.ValueType() != wire.TStruct {
		return nil, nil
	}
	o := make([]*broker.BackendStatus, 0, l.Size())
	err := l.ForEach(func(x wire.Value) error {
		i, err := _BackendStatus_Read(x)
		if err != nil {
			return err
		}
		o = append(o, i)
		return nil
	})
	l.Close()
	return o, err
}

func (v *BackendsResult) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TList {
				v.Success, err = _List_BackendStatus_Read(field.Value.GetList())
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("BackendsResult should have exactly one field: got %v fields", count)
	}
	return nil
}

func (v *BackendsResult) String() string {
	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}
	return fmt.Sprintf("BackendsResult{%v}", strings.Join(fields[:i], ", "))
}

func (v *BackendsResult) MethodName() string {
	return "backends"
}

func (v *BackendsResult) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}

var BackendsHelper = struct {
	IsException    func(error) bool
	Args           func() *BackendsArgs
	WrapResponse   func([]*broker.BackendStatus, error) (*BackendsResult, error)
	UnwrapResponse func(*BackendsResult) ([]*broker.BackendStatus, error)
}{}

func init() {
	BackendsHelper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}
	BackendsHelper.Args = func() *BackendsArgs {
		return &BackendsArgs{}
	}
	BackendsHelper.WrapResponse = func(success []*broker.BackendStatus, err error) (*BackendsResult, error) {
		if err == nil {
			return &BackendsResult{Success: success}, nil
		}
		return nil, err
	}
	BackendsHelper.UnwrapResponse = func(result *BackendsResult) (success []*broker.BackendStatus, err error) {
		if result.Success != nil {
			success = result.Success
			return
		}
		err = errors.New("expected a non-void result")
		return
	}
}
