// Code generated by thriftrw

package loadbalancer

import (
	"fmt"
	"github.com/thriftrw/thriftrw-go/wire"
	"strings"
)

type DelBackendArgs struct {
	Endpoint *string `json:"endpoint,omitempty"`
}

func (v *DelBackendArgs) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Endpoint != nil {
		w, err = wire.NewValueString(*(v.Endpoint)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *DelBackendArgs) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.Endpoint = &x
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (v *DelBackendArgs) String() string {
	var fields [1]string
	i := 0
	if v.Endpoint != nil {
		fields[i] = fmt.Sprintf("Endpoint: %v", *(v.Endpoint))
		i++
	}
	return fmt.Sprintf("DelBackendArgs{%v}", strings.Join(fields[:i], ", "))
}

func (v *DelBackendArgs) MethodName() string {
	return "del_backend"
}

func (v *DelBackendArgs) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

type DelBackendResult struct{}

func (v *DelBackendResult) ToWire() (wire.Value, error) {
	var (
		fields [0]wire.Field
		i      int = 0
	)
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func (v *DelBackendResult) FromWire(w wire.Value) error {
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		}
	}
	return nil
}

func (v *DelBackendResult) String() string {
	var fields [0]string
	i := 0
	return fmt.Sprintf("DelBackendResult{%v}", strings.Join(fields[:i], ", "))
}

func (v *DelBackendResult) MethodName() string {
	return "del_backend"
}

func (v *DelBackendResult) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}

var DelBackendHelper = struct {
	IsException    func(error) bool
	Args           func(endpoint *string) *DelBackendArgs
	WrapResponse   func(error) (*DelBackendResult, error)
	UnwrapResponse func(*DelBackendResult) error
}{}

func init() {
	DelBackendHelper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}
	DelBackendHelper.Args = func(endpoint *string) *DelBackendArgs {
		return &DelBackendArgs{Endpoint: endpoint}
	}
	DelBackendHelper.WrapResponse = func(err error) (*DelBackendResult, error) {
		if err == nil {
			return &DelBackendResult{}, nil
		}
		return nil, err
	}
	DelBackendHelper.UnwrapResponse = func(result *DelBackendResult) (err error) {
		return
	}
}
