// Code generated by thriftrw

package brokerclient

import (
	"github.com/bombela/yarpc-go-fun/broker/service/broker"
	"github.com/thriftrw/thriftrw-go/protocol"
	"github.com/thriftrw/thriftrw-go/wire"
	yarpc "github.com/yarpc/yarpc-go"
	"github.com/yarpc/yarpc-go/encoding/thrift"
	"github.com/yarpc/yarpc-go/transport"
)

type Interface interface {
	Poll(reqMeta yarpc.CallReqMeta, key *string, maxMsgs *int32) ([]string, yarpc.CallResMeta, error)
	Publish(reqMeta yarpc.CallReqMeta, topic *string, message *string) (yarpc.CallResMeta, error)
	Subscribe(reqMeta yarpc.CallReqMeta, topic *string) (string, yarpc.CallResMeta, error)
}

func New(c transport.Channel) Interface {
	return client{c: thrift.New(thrift.Config{Service: "Broker", Channel: c, Protocol: protocol.Binary})}
}

type client struct{ c thrift.Client }

func (c client) Poll(reqMeta yarpc.CallReqMeta, key *string, maxMsgs *int32) (success []string, resMeta yarpc.CallResMeta, err error) {
	args := broker.PollHelper.Args(key, maxMsgs)
	var body wire.Value
	body, resMeta, err = c.c.Call(reqMeta, args)
	if err != nil {
		return
	}
	var result broker.PollResult
	if err = result.FromWire(body); err != nil {
		return
	}
	success, err = broker.PollHelper.UnwrapResponse(&result)
	return
}

func (c client) Publish(reqMeta yarpc.CallReqMeta, topic *string, message *string) (resMeta yarpc.CallResMeta, err error) {
	args := broker.PublishHelper.Args(topic, message)
	var body wire.Value
	body, resMeta, err = c.c.Call(reqMeta, args)
	if err != nil {
		return
	}
	var result broker.PublishResult
	if err = result.FromWire(body); err != nil {
		return
	}
	err = broker.PublishHelper.UnwrapResponse(&result)
	return
}

func (c client) Subscribe(reqMeta yarpc.CallReqMeta, topic *string) (success string, resMeta yarpc.CallResMeta, err error) {
	args := broker.SubscribeHelper.Args(topic)
	var body wire.Value
	body, resMeta, err = c.c.Call(reqMeta, args)
	if err != nil {
		return
	}
	var result broker.SubscribeResult
	if err = result.FromWire(body); err != nil {
		return
	}
	success, err = broker.SubscribeHelper.UnwrapResponse(&result)
	return
}
